version: '3'

services:
  couchdb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5984:5984'
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: secret
    volumes:
      - couchdb-database:/opt/couchdb/data

volumes:
  couchdb-database:
